### PR TITLE
CI runs

### PR DESCRIPTION
**Pull request by stonedDiscord**
This will automatically build RVLoader and the SD Card files.

I also fixed the Makefile, the rule to create $(OUTPUT).dol needs to get it from somewhere, in this case we can just copy the elf file

### CODE REVIEW

**Comment by Aurelio92** [comment]
Why do you copy the ELF build into a DOL?

**Comment by stonedDiscord** [comment]
because there is no DOL file and make fails with
`cp: cannot stat '/__w/RVLoader/RVLoader/bootloader/bootloader.dol': No such file or directory`

**Comment by stonedDiscord** [comment]
nevermind i misunderstood the makefile
it now correctly converts the elf to a dol

**Comment by Aurelio92** [comment]
You shouldn't need to use elf2dol manually, devkitppc base rules already integrate it. I will check everything better tomorrow when I get back home

**Comment by Aurelio92** [comment]
I had to do few changes to the Makefiles to let them properly build dols using wii_rules. Now it seems like everything works as intended. Thanks for the contribution!

**Pull request merged**
